[book]
authors = ["jingdor"]
language = "en"
multilingual = false
src = "src"

[preprocessor.example]
renderers = ["html"]
command = "python3 preprocessors/example.py"

#[output.backends]
#command = "python3 ../../backends/backends.py"
#renderer = ["html"]

[output.html]
additional-css = ["xterm.css"]
additional-js = ["xterm.js","xterm-addon-fit.js"]

[output.html.playground]
editable = true
copy-js = true
line-numbers = true


